mysql1:
  image: mysql:latest
  expose:
   - "3306"
  environment:
   - MYSQL_ROOT_PASSWORD=123456
   - MYSQL_DATABASE=kingshard
  volumes:
   - ./db/mysql1:/var/lib/mysql

mysql2:
  image: mysql:latest
  expose:
   - "3306"
  environment:
   - MYSQL_ROOT_PASSWORD=123456
   - MYSQL_DATABASE=kingshard
  volumes:
   - ./db/mysql1:/var/lib/mysql

kingshard:
  image: kingshard
  volumes:
    - .:/go/src/github.com/flike/kingshard/etc
  ports:
    - "9696:9696"
  expose:
    - "9696"
  links:
    - mysql1
    - mysql2
  entrypoint: /go/src/github.com/flike/kingshard/etc/run.sh
